---

- name: Disable hibernation (speeds up entering sleep mode)
  command: "pmset -a hibernatemode 0"
  become: true
  become_method: sudo

- name: Remove the sleep image file to save disk space
  file: 
    path: "{{sleep_image_file_path}}"
    state: absent
  become: true
  become_method: sudo

# - name: Create a zero-byte file instead previously deleted sleep image
#   file: 
#     path: "{{sleep_image_file_path}}"
#     state: touch

# - name: Make sure that a sleep image can’t be rewritten
#   command: "chflags uchg {{sleep_image_file_path}}"

- name: Disable the sudden motion sensor as it’s not useful for SSDs
  command: "pmset -a sms 0"
  become: true
  become_method: sudo
