---
sudo: required

os:
  - osx

osx_image:
  # OS X 10.15.5
  - xcode12

cache:
  - directories:
    # Python
    - $HOME/.pyenv
    # Python virtual environment
    - .venv


install:
  - make setup
  - source .venv/bin/activate

script:
  - make test run_all
  - git s
