---
sudo: required

os:
  - osx

osx_image:
  # OS X 10.15.5
  - xcode12

cache:
  - directories:
    # Python
    - $HOME/.pyenv
    # Python virtual environment
    - .venv


install:
  - make setup
  - source .venv/bin/activate

script:
  - ansible-playbook -i inventory --syntax-check local_env.yml
  - ansible-playbook -i inventory local_env.yml --tags macos
  - ansible-playbook -i inventory local_env.yml --tags zsh
  - ansible-playbook -i inventory local_env.yml --tags iterm2
  - ansible-playbook -i inventory local_env.yml --tags dotfiles
  - git s
