homebrew_taps_user:
  - hashicorp/tap

homebrew_installed_packages:
  - awscli
  - kubectl
  - terraform
  - localstack
  - poetry
  - tmux

homebrew_cask_apps_user:
  - intellij-idea-ce
  - google-chrome
  - slack
  - notion
  - whatsapp
  - zoom

oh_my_zsh_plugins_user:
  - aws
  - kubectl
