---
user_home: "{{ '~' | expanduser }}"

install_homebrew_if_missing: true
brew_path: "{{ '/opt/homebrew/bin/brew' if ansible_architecture == 'arm64' else '/usr/local/bin/brew' }}"

iterm_dynamic_profiles_dir: "{{user_home}}/Library/Application Support/iTerm2/DynamicProfiles"

homebrew_installed_packages:
  - coreutils
  - duf
  - findutils
  - git
  - git-lfs
  - curl
  - wget
  - openssl
  - pango
  - cairo
  - pkg-config
  - libpng
  - jpeg
  - giflib
  - librsvg
  # GitHub CLI
  - gh
  - pyenv
  # - hey
  # https://dev.to/lissy93/cli-tools-you-cant-live-without-57f6
  - tldr
  - duf
  - bat
  - diff-so-fancy
  - jq
  - procs
  - tre
  - bandwhich
  - ctop
  - bpytop
  - dua-cli
  - lazygit
  - fzf
  - ripgrep
  - fd
  - nvim
  - uv

# Mac Apps to be installed with homebrew-cask
homebrew_cask_apps:
  # https://github.com/tonsky/FiraCode
  - font-fira-code
  # https://iterm2.com/
  - iterm2
  # https://orbstack.dev/
  - orbstack
  # https://zed.dev/
  - zed
  # https://meld.app/
  - meld

oh_my_zsh_home: "{{user_home}}/.oh-my-zsh"
oh_my_zsh_theme: "powerlevel10k/powerlevel10k"
oh_my_zsh_custom_plugins:
  - name: zsh-syntax-highlighting
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    version: 754cefe0181a7acd42fdcb357a67d0217291ac47
  - name: zsh-autosuggestions
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    version: a411ef3e0992d4839f0732ebeb9823024afaaaa8
  - name: zsh-completions
    repo: "https://github.com/zsh-users/zsh-completions.git"
    version: 98ea8e685c1a9630a21b39a1596cb94794d1cb3c
  - name: zsh-nvm
    repo: "https://github.com/lukechilds/zsh-nvm.git"
    version: 745291dcf20686ec421935f1c3f8f3a2918dd106

oh_my_zsh_custom_themes:
  - name: powerlevel10k
    repo: "https://github.com/romkatv/powerlevel10k.git"
    version: v1.17.0

oh_my_zsh_plugins:
  - git
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - z
  - zsh-nvm
