- name: Generate ssh keys
  openssh_keypair:
    path: "{{ ssh_home }}/{{ item.name }}"
    type: "{{ item.type }}"
    size: "{{ item.size }}"
  with_items: "{{ ssh_keys }}"

- set_fact:
    ssh_config_content: "{{ lookup('template', 'templates/ssh.config.j2') }}"

- name: Create ssh config file
  blockinfile:
    create: yes
    dest: "{{ ssh_home }}/config"
    content: "{{ ssh_config_content }}"
    mode: 0640
  tags: configuration
