---

- name: "[ActivityMonitor] Show the main window when launching Activity Monitor"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true

# Dock Icon Possible Options:
# 0: Application Icon
# 2: Network Usage
# 3: Disk Activity
# 5: CPU Usage
# 6: CPU History

- name: "[ActivityMonitor] Visualize CPU usage in the Activity Monitor Dock icon"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5

- name: "[ActivityMonitor] Show all processes in Activity Monitor"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0

- name: "[ActivityMonitor] Sort Activity Monitor results by CPU usage"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"

- name: "[ActivityMonitor] Sort Activity Monitor results by CPU usage"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0
