---

- name: "[Finder] Allow quitting via ⌘ + Q; doing so will also hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true

- name: "[Finder] Disable window animations and Get Info animations"
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true

- name: "[Finder] Set Desktop as the default location for new Finder windows"
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://{{user_home}}}/Desktop/"

- name: "[Finder] For other paths, use `PfLo` and `file:///full/path/here/`"
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfDe"

- name: "[Finder] Show icons for external hard drives on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for hard drives on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for mounted servers on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for removable media on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true

- name: "[Finder] Show hidden files by default"
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: "[Finder] Show all filename extensions"
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: "[Finder] Show status bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: "[Finder] Show path bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: "[Finder] Allow text selection in Quick Look"
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

- name: "[Finder] Display full POSIX path as Finder window title"
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

- name: "[Finder] When performing a search, search the current folder by default"
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

- name: "[Finder] Disable the warning when changing a file extension"
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: "[Finder] Disable the warning before emptying the Trash"
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: "[Finder] Use list view in all Finder windows by default"
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "Nlsv"

- name: "[Finder] Empty Trash securely by default"
  osx_defaults:
    domain: com.apple.finder
    key: EmptyTrashSecurely
    type: bool
    value: true

- name: "[Finder] Enable spring loading for directories"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true

- name: "[Finder] Remove the spring loading delay for directories"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 0

- name: "[Finder] Avoid creating .DS_Store files on network volumes"
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: "[Finder] Disable disk image verification"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify
    type: bool
    value: true

- name: "[Finder] Disable disk image verification - locked"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-locked
    type: bool
    value: true

- name: "[Finder] Disable disk image verification - remove"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-remote
    type: bool
    value: true

- name: "[Finder] Automatically open a new Finder window when a volume is mounted"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true

- name: "[Finder] Automatically open a new Finder window when a volume is mounted"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-rw-root
    type: bool
    value: true

- name: "[Finder] Automatically open a new Finder window when a volume is mounted"
  osx_defaults:
    domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: true

- name: "[Finder] Enable AirDrop over Ethernet and on unsupported Macs running Lion"
  osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true

- name: "[Finder] Show the ~/Library folder"
  command: "chflags nohidden ~/Library"
