---
- name: "[Keyboard] Set keyboard repeat rate"
  osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: integer
    value: 15
    state: present

- name: "[Keyboard] Set keyboard delay rate"
  osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: integer
    value: 2
    state: present
