---

- name: Save to disk (not to iCloud) by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: Automatically quit printer app once the print jobs complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present

- name: Disable hibernation (speeds up entering sleep mode)
  command: "pmset -a hibernatemode 0"
  become: true
  become_method: sudo

- name: Remove the sleep image file to save disk space
  file: 
    path: "{{sleep_image_file_path}}"
    state: absent
  become: true
  become_method: sudo

# - name: Create a zero-byte file instead previously deleted sleep image
#   file: 
#     path: "{{sleep_image_file_path}}"
#     state: touch

# - name: Make sure that a sleep image can’t be rewritten
#   command: "chflags uchg {{sleep_image_file_path}}"

- name: Disable the sudden motion sensor as it’s not useful for SSDs
  command: "pmset -a sms 0"
  become: true
  become_method: sudo
  
- name: Set Trackpad Settings
  import_tasks: trackpad.yml

- name: Disable “natural” (Lion-style) scrolling
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present


- name: Set AppleMeasurementUnits to Centimeters
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
    state: present

- name: Set AppleLanguages to English & Hebrew
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en-US
      - he-US

- name: Set AppleLocale to en_US@currency=USD
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "en_US@currency=USD"

- name: Set AppleMetricUnits=true
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true

- name: Set the timezone
  command: "systemsetup -settimezone \"Asia/Jerusalem\" > /dev/null"

- name: Disable auto-correct
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Set Screenshot Settings
  import_tasks: screenshot.yml

- name: Set Finder Settings
  import_tasks: finder.yml

- name: Set Dock Settings
  import_tasks: dock.yml

- name: "[Dashboard] Disable Dashboard"
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true

- name: "[Dashboard] Don’t show Dashboard as a Space"
  osx_defaults:
    domain: com.apple.dashboard
    key: dashboard-in-overlay
    type: bool
    value: true

- name: Set Activity Monitor Settings
  import_tasks: activity_monitor.yml
