---

- name: Save to disk (not to iCloud) by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: Automatically quit printer app once the print jobs complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present

- name: Disable hibernation (speeds up entering sleep mode)
  command: "pmset -a hibernatemode 0"

- name: Remove the sleep image file to save disk space
  file: 
    path: "{{sleep_image_file_path}}"
    state: absent

# - name: Create a zero-byte file instead previously deleted sleep image
#   file: 
#     path: "{{sleep_image_file_path}}"
#     state: touch

# - name: Make sure that a sleep image can’t be rewritten
#   command: "chflags uchg {{sleep_image_file_path}}"

- name: Disable the sudden motion sensor as it’s not useful for SSDs
  command: "pmset -a sms 0"

- name: "Trackpad [Bluetooth]: enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 0
    state: present

- name: "Mouse [TapBehavior, currentHost]: enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    host: currentHost
    type: int
    value: 1
    state: present

- name: "Mouse [TapBehavior]: enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
    state: present

- name: "Trackpad [CornerSecondaryClick]: map bottom right corner to right-click"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
    state: present

- name: "Trackpad [RightClick]: map bottom right corner to right-click"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: bool
    value: true
    state: present

- name: "Trackpad [CornerClickBehavior]: map bottom right corner to right-click"
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.trackpad.trackpadCornerClickBehavior
    type: int
    value: 1
    state: present

- name: "Trackpad [EnableSecondaryClick]: map bottom right corner to right-click"
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.trackpad.enableSecondaryClick
    type: bool
    value: true
    state: present

- name: Disable “natural” (Lion-style) scrolling
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present


- name: Set AppleMeasurementUnits to Centimeters
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
    state: present

- name: Set AppleLanguages to English & Hebrew
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en-US
      - he-US

- name: Set AppleLocale to en_US@currency=USD
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "en_US@currency=USD"

- name: Set AppleMetricUnits=true
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true

- name: Set the timezone
  command: "systemsetup -settimezone \"Asia/Jerusalem\" > /dev/null"

- name: Disable auto-correct
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Save screenshots to the desktop
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{user_home}}/Desktop"

- name: "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png

- name: "[Finder] Allow quitting via ⌘ + Q; doing so will also hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true

- name: "[Finder] Disable window animations and Get Info animations"
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true

- name: "[Finder] Set Desktop as the default location for new Finder windows"
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://{{user_home}}}/Desktop/"

- name: "[Finder] For other paths, use `PfLo` and `file:///full/path/here/`"
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfDe"

- name: "[Finder] Show icons for external hard drives on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for hard drives on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for mounted servers on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for removable media on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true
