---

- name: Set SSD Settings
  import_tasks: system/ssd.yml

- name: Set Miscellaneous Settings
  import_tasks: misc.yml
  
- name: Set Trackpad Settings
  import_tasks: trackpad.yml

- name: Set Locale Settings
  import_tasks: locale.yml

- name: Set Screenshot Settings
  import_tasks: screenshot.yml

- name: Set Finder Settings
  import_tasks: finder.yml

- name: Set Dock Settings
  import_tasks: dock.yml

- name: Set Dashboard Settings
  import_tasks: dashboard.yml

- name: Set Activity Monitor Settings
  import_tasks: activity_monitor.yml

- name: Set Keyboard Settings
  import_tasks: keyboard.yml
