---

- name: Save to disk (not to iCloud) by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: Automatically quit printer app once the print jobs complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present

- name: Disable hibernation (speeds up entering sleep mode)
  command: "pmset -a hibernatemode 0"

- name: Remove the sleep image file to save disk space
  file: 
    path: "{{sleep_image_file_path}}"
    state: absent

# - name: Create a zero-byte file instead previously deleted sleep image
#   file: 
#     path: "{{sleep_image_file_path}}"
#     state: touch

# - name: Make sure that a sleep image can’t be rewritten
#   command: "chflags uchg {{sleep_image_file_path}}"

- name: Disable the sudden motion sensor as it’s not useful for SSDs
  command: "pmset -a sms 0"

- name: "Trackpad [Bluetooth]: enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 0
    state: present

- name: "Mouse [TapBehavior, currentHost]: enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    host: currentHost
    type: int
    value: 1
    state: present

- name: "Mouse [TapBehavior]: enable tap to click for this user and for the login screen"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1
    state: present

- name: "Trackpad [CornerSecondaryClick]: map bottom right corner to right-click"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
    state: present

- name: "Trackpad [RightClick]: map bottom right corner to right-click"
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: bool
    value: true
    state: present

- name: "Trackpad [CornerClickBehavior]: map bottom right corner to right-click"
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.trackpad.trackpadCornerClickBehavior
    type: int
    value: 1
    state: present

- name: "Trackpad [EnableSecondaryClick]: map bottom right corner to right-click"
  osx_defaults:
    host: currentHost
    domain: NSGlobalDomain
    key: com.apple.trackpad.enableSecondaryClick
    type: bool
    value: true
    state: present

- name: Disable “natural” (Lion-style) scrolling
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present


- name: Set AppleMeasurementUnits to Centimeters
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: Centimeters
    state: present

- name: Set AppleLanguages to English & Hebrew
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en-US
      - he-US

- name: Set AppleLocale to en_US@currency=USD
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "en_US@currency=USD"

- name: Set AppleMetricUnits=true
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true

- name: Set the timezone
  command: "systemsetup -settimezone \"Asia/Jerusalem\" > /dev/null"

- name: Disable auto-correct
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Save screenshots to the desktop
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{user_home}}/Desktop"

- name: "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png

- name: "[Finder] Allow quitting via ⌘ + Q; doing so will also hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true

- name: "[Finder] Disable window animations and Get Info animations"
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true

- name: "[Finder] Set Desktop as the default location for new Finder windows"
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://{{user_home}}}/Desktop/"

- name: "[Finder] For other paths, use `PfLo` and `file:///full/path/here/`"
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfDe"

- name: "[Finder] Show icons for external hard drives on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for hard drives on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for mounted servers on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: true

- name: "[Finder] Show icons for removable media on the desktop"
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true

- name: "[Finder] Show hidden files by default"
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- name: "[Finder] Show all filename extensions"
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: "[Finder] Show status bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: "[Finder] Show path bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: "[Finder] Allow text selection in Quick Look"
  osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

- name: "[Finder] Display full POSIX path as Finder window title"
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true

- name: "[Finder] When performing a search, search the current folder by default"
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

- name: "[Finder] Disable the warning when changing a file extension"
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: "[Finder] Disable the warning before emptying the Trash"
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: "[Finder] Use list view in all Finder windows by default"
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "Nlsv"

- name: "[Finder] Empty Trash securely by default"
  osx_defaults:
    domain: com.apple.finder
    key: EmptyTrashSecurely
    type: bool
    value: true

- name: "[Finder] Enable spring loading for directories"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true

- name: "[Finder] Remove the spring loading delay for directories"
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 0

- name: "[Finder] Avoid creating .DS_Store files on network volumes"
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: "[Finder] Disable disk image verification"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify
    type: bool
    value: true

- name: "[Finder] Disable disk image verification - locked"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-locked
    type: bool
    value: true

- name: "[Finder] Disable disk image verification - remove"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: skip-verify-remote
    type: bool
    value: true

- name: "[Finder] Automatically open a new Finder window when a volume is mounted"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true

- name: "[Finder] Automatically open a new Finder window when a volume is mounted"
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-rw-root
    type: bool
    value: true

- name: "[Finder] Automatically open a new Finder window when a volume is mounted"
  osx_defaults:
    domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: true

- name: "[Finder] Enable AirDrop over Ethernet and on unsupported Macs running Lion"
  osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: true

- name: "[Finder] Show the ~/Library folder"
  command: "chflags nohidden ~/Library"

- name: "[Dock] Enable highlight hover effect for the grid view of a stack"
  osx_defaults:
    domain: com.apple.dock
    key: mouse-over-hilite-stack
    type: bool
    value: true

- name: "[Dock] Set the icon size of Dock items to 36 pixels"
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 36

- name: "[Dock] Change minimize/maximize window effect"
  osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: "scale"

- name: "[Dock] Minimize windows into their application’s icon"
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true

- name: "[Dock] Enable spring loading for all Dock items"
  osx_defaults:
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: true

- name: "[Dock] Show indicator lights for open applications in the Dock"
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true

- name: "[Dock] Don’t animate opening applications from the Dock"
  osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false

- name: "[Dock] Speed up Mission Control animations"
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1

- name: "[Dock] Don’t group windows by application in Mission Control"
  osx_defaults:
    domain: com.apple.dock
    key: expose-group-by-app
    type: bool
    value: false

- name: "[Dock] Don’t automatically rearrange Spaces based on most recent use"
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

- name: "[Dock] Remove the auto-hiding Dock delay"
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0

- name: "[Dock] Remove the animation when hiding/showing the Dock"
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0

- name: "[Dock] Automatically hide and show the Dock"
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: "[Dock] Make Dock icons of hidden applications translucent"
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true

- name: "[Dock] Make Dock more transparent"
  osx_defaults:
    domain: com.apple.dock
    key: hide-mirror
    type: bool
    value: true

- name: "[Dock] Reset Launchpad"
  command: "find ~/Library/Application\ Support/Dock -name \"*.db\" -maxdepth 1 -delete"

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center

- name: "[Dock] Top left screen corner → Mission Control"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 2

- name: "[Dock] Top left screen corner → Mission Control"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0


- name: "[Dock] Top right screen corner → Desktop"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-corner
    type: int
    value: 4

- name: "[Dock] Top right screen corner → Desktop"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-tr-modifier
    type: int
    value: 0

- name: "[Dock] Bottom left screen corner → Start screen saver"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: 5

- name: "[Dock] Bottom left screen corner → Start screen saver"
  osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: 0


- name: "[Dashboard] Disable Dashboard"
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true

- name: "[Dashboard] Don’t show Dashboard as a Space"
  osx_defaults:
    domain: com.apple.dashboard
    key: dashboard-in-overlay
    type: bool
    value: true

- name: "[iTerm2] Don’t display the annoying prompt when quitting iTerm"
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false

- name: "[ActivityMonitor] Show the main window when launching Activity Monitor"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true

- name: "[ActivityMonitor] Visualize CPU usage in the Activity Monitor Dock icon"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5

- name: "[ActivityMonitor] Show all processes in Activity Monitor"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0

- name: "[ActivityMonitor] Sort Activity Monitor results by CPU usage"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"

- name: "[ActivityMonitor] Sort Activity Monitor results by CPU usage"
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0