---

- name: Save screenshots to the desktop
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{user_home}}/Desktop"

- name: Include date in screenshots
  osx_defaults:
    domain: com.apple.screencapture
    key: include-date
    type: bool
    value: true
    state: present

- name: "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
