install_oh_my_zsh: yes

oh_my_zsh_home: "{{user_home}}/.oh-my-zsh"
powerline_fonts_home: "{{user_home}}/.powerline-fonts"

zsh_user:
  - "{{ ansible_ssh_user|default(lookup('env', 'USER'))  }}"

zsh_debug_startup_time: false
oh_my_zsh_theme: agnoster
zsh_append_zshrc: ""

oh_my_zsh_custom_plugins:
  - name: zsh-syntax-highlighting
    repo: "git://github.com/zsh-users/zsh-syntax-highlighting.git"
  - name: zsh-autosuggestions
    repo: "git://github.com/zsh-users/zsh-autosuggestions.git"
  - name: zsh-completions
    repo: "git://github.com/zsh-users/zsh-completions.git"

oh_my_zsh_custom_themes:
  - name: powerlevel9k
    repo: "https://github.com/bhilburn/powerlevel9k.git"

oh_my_zsh_plugins:
  - git
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions