---

- name: "[Screenshots] Save screenshots to the desktop"
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "file://{{ user_home }}}/Desktop/"

- name: "[Screenshots] Include date in screenshots"
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: include-date
    type: bool
    value: true
    state: present

- name: "[Screenshots] Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: png
