name: ci-workflow

on:
  schedule:
      # Weekly, at 00:00 on Sunday
    - cron: "0 0 * * 0"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
    - uses: actions/checkout@v2
    - name: Install coreutils
      run: |
        brew install coreutils
    - name: setup virtual environment
      run: |
        make setup
    - name: check syntax
      run: |
        make test-syntax
    - name: sanity
      run: |
        make run-all
    - name: clean
      run: |
        make clean
