name: ci-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install coreutils
      run: |
        brew install coreutils
    - name: setup virtual environment
      run: |
        make setup
    - name: check syntax
      run: |
        make test-syntax
    - name: sanity
      run: |
        make run-all
    - name: clean
      run: |
        make clean
