---

name: ci-workflow

on:
  schedule:
    # Weekly, at 00:00 on Sunday
    - cron: "0 0 * * 0"
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Setup
        run: >
          ./setup.sh

      - name: Lint
        run: |
          source activate.sh
          ansible-lint
          ansible-playbook main.yml --syntax-check

      - name: Homebrew sanity
        run: |
          source activate.sh
          ansible-playbook main.yml --tags "homebrew"
